export const objList = [
    { name: 'box', label: '正方体', thumbnail: './glb/thumbnail/box.png'  },
    { name: 'sphere', label: '球', thumbnail: './glb/thumbnail/sphere.png'  },
    { name: 'cone', label: '园锥体', thumbnail: './glb/thumbnail/cone.png'  },
    { name: 'cylinder', label: '园柱体', thumbnail: './glb/thumbnail/cylinder.png'  },
    { name: 'cylindereight', label: '八棱柱体', thumbnail: './glb/thumbnail/cylinder.png'  },
    { name: 'shapea', label: '形状a', thumbnail: './glb/thumbnail/shapea.png'  },
    { name: 'conecrossfourside', label: '形状b', thumbnail: './glb/thumbnail/shapeb.png'  },
    { name: 'conecross', label: '圆锥穿插体', thumbnail: './glb/thumbnail/shapec.png'  },
    { name: 'shaped', label: '形状d', thumbnail: './glb/thumbnail/shaped.png'  },
    { name: 'coffeeCup', label: '咖啡杯', thumbnail: './glb/thumbnail/coffeeCup.png'  },
    { name: 'bust', label: '石膏像', thumbnail: './glb/thumbnail/bust.png'  },
    { name: 'foot', label: '脚', thumbnail: './glb/thumbnail/foot.png'  },
    { name: 'bottle', label: '瓶子', thumbnail: './glb/thumbnail/bottle.png'  },
    { name: 'venus', label: '维纳斯', thumbnail: './glb/thumbnail/venus.png'  },
    { name: 'bowl', label: '碗', thumbnail: './glb/thumbnail/bowl.png'  },
    { name: 'butterknife', label: '黄油刀', thumbnail: './glb/thumbnail/butterknife.png'  },
    { name: 'cup', label: '杯', thumbnail: './glb/thumbnail/cup.png'  },
    { name: 'cuphandle', label: '手柄杯子', thumbnail: './glb/thumbnail/cuphandle.png'  },
    { name: 'fork', label: '叉子', thumbnail: './glb/thumbnail/fork.png'  },
    { name: 'plate', label: '盘子', thumbnail: './glb/thumbnail/plate.png'  },
    // { name: 'pot', label: '锅', thumbnail: './glb/thumbnail/pot.png'  },
    { name: 'scoop', label: '勺', thumbnail: './glb/thumbnail/scoop.png'  },
    { name: 'scoopstuff', label: '铲子', thumbnail: './glb/thumbnail/scoopstuff.png'  },
    { name: 'spatula', label: '铲子', thumbnail: './glb/thumbnail/spatula.png'  },
    { name: 'spoon', label: '勺子', thumbnail: './glb/thumbnail/spoon.png'  },
    { name: 'fryingpan', label: '煎锅', thumbnail: './glb/thumbnail/fryingpan.png'  },
    { name: 'apple', label: '苹果', thumbnail: './glb/thumbnail/apple.png'  },
    { name: 'pear', label: '梨', thumbnail: './glb/thumbnail/pear.png'  },
    { name: 'apricot', label: '杏子', thumbnail: './glb/thumbnail/apricot.png'  },
    { name: 'banana', label: '香蕉', thumbnail: './glb/thumbnail/banana.png'  },
];
