
export const objList = [
    { component: 'Box', name: 'box', label: '正方体', thumbnail: './glb/thumbnail/box.png' },
    { component: 'Sphere', name: 'sphere', label: '球', thumbnail: './glb/thumbnail/sphere.png' },
    { component: 'Cone', name: 'cone', label: '园锥体', thumbnail: './glb/thumbnail/cone.png' },
    { component: 'Cylinder', name: 'cylinder', label: '园柱体', thumbnail: './glb/thumbnail/cylinder.png' },
    { component: 'CylinderEight', name: 'cylindereight', label: '八棱柱体', thumbnail: './glb/thumbnail/cylinder.png' },
    { component: 'ShapeA', name: 'shapea', label: '形状a', thumbnail: './glb/thumbnail/shapea.png' },
    { component: 'ConeCrossFourSide', name: 'conecrossfourside', label: '形状b', thumbnail: './glb/thumbnail/conecrossfourside.png' },
    { component: 'ConeCross', name: 'conecross', label: '圆锥穿插体', thumbnail: './glb/thumbnail/conecross.png' },
    { component: 'BoxCross', name: 'boxcross', label: '十字穿插体', thumbnail: './glb/thumbnail/boxcross.png' },
    { component: 'Icosahedron', name: 'icosahedron', label: '多面', thumbnail: './glb/thumbnail/icosahedron.png' },
    { component: 'Dodecahedron', name: 'dodecahedron', label: '正十二面体', thumbnail: './glb/thumbnail/dodecahedron.png' },
    { component: 'CupHandle', name: 'cupHandle', label: '手柄杯', thumbnail: './glb/thumbnail/cuphandle.png' },
    { component: 'CupHandleB', name: 'cupHandleB', label: '手柄杯2', thumbnail: './glb/thumbnail/cuphandleb.png' },
    { component: 'CupHandleC', name: 'cupHandleC', label: '手柄杯3', thumbnail: './glb/thumbnail/cuphandlec.png' },
    { component: 'PlateA', name: 'PlateA', label: '盘子A', thumbnail: './glb/thumbnail/platea.png' },
    { component: 'PlateB', name: 'PlateB', label: '盘子B', thumbnail: './glb/thumbnail/plateb.png' },
    { component: 'PlateC', name: 'PlateC', label: '盘子C', thumbnail: './glb/thumbnail/platec.png' },
    { component: 'Goblet', name: 'goblet', label: '高脚杯', thumbnail: './glb/thumbnail/goblet.png' },
    { component: 'WineBottle', name: 'winebottle', label: '酒瓶', thumbnail: './glb/thumbnail/winebottle.png' },
    { component: 'Egg', name: 'egg', label: '鸡蛋', thumbnail: './glb/thumbnail/egg.png' },
    { component: 'Pear', name: 'pear', label: '鸡蛋', thumbnail: './glb/thumbnail/pear.png' },
    { component: 'Apple', name: 'apple', label: '苹果', thumbnail: './glb/thumbnail/apple.png' },
    { component: 'JarA', name: 'jara', label: '坛子a', thumbnail: './glb/thumbnail/jara.png' },
    { component: 'JarB', name: 'jarb', label: '坛子b', thumbnail: './glb/thumbnail/jarb.png' },
    { component: 'Vasea', name: 'vasea', label: '花瓶a', thumbnail: './glb/thumbnail/vasea.png' },
    { component: 'Vaseb', name: 'vaseb', label: '花瓶a', thumbnail: './glb/thumbnail/vaseb.png' },
    { component: 'Vasec', name: 'vasec', label: '花瓶a', thumbnail: './glb/thumbnail/vasec.png' },
    { component: 'body/Eye', name: 'eye', label: '眼睛', thumbnail: './glb/thumbnail/body/eye.png' },
    { component: 'body/Foot', name: 'foot', label: '脚', thumbnail: './glb/thumbnail/body/foot.png' },
    { component: 'body/Venus', name: 'venus', label: '维纳斯', thumbnail: './glb/thumbnail/body/venus.png' },
    { component: 'body/FemaleBody', name: 'femalebody', label: '女性身体', thumbnail: './glb/thumbnail/body/femalebody.png' },
    { component: 'body/MaleBody', name: 'malebody', label: '男性身体', thumbnail: './glb/thumbnail/body/malebody.png' },
    { component: 'body/Skeleton', name: 'skeleton', label: '骷髅', thumbnail: './glb/thumbnail/body/skeleton.png' },
    { component: 'body/SkeletonB', name: 'skeleton_b', label: '骷髅', thumbnail: './glb/thumbnail/body/skeleton_b.png' },
    { component: 'body/LoomisHead', name: 'loomis_head', label: 'loomis_head', thumbnail: './glb/thumbnail/body/loomis_head.png' },
    { component: 'body/SkeletonHead', name: 'skeleton_head', label: 'skeleton_head', thumbnail: './glb/thumbnail/body/skeleton_head.png' },
    { component: 'body/HeadReference', name: 'head_reference', label: 'head_reference', thumbnail: './glb/thumbnail/body/head_reference.png' },
];

