
export const objList = [
    {checkedlocked: false, component: 'Box', name: 'box', label: '正方体', thumbnail: './glb/thumbnail/box.png' },
    {checkedlocked: false, component: 'Sphere', name: 'sphere', label: '球', thumbnail: './glb/thumbnail/sphere.png' },
    {checkedlocked: false, component: 'Cone', name: 'cone', label: '园锥体', thumbnail: './glb/thumbnail/cone.png' },
    {checkedlocked: false, component: 'Cylinder', name: 'cylinder', label: '园柱体', thumbnail: './glb/thumbnail/cylinder.png' },
    {checkedlocked: false, component: 'CylinderEight', name: 'cylindereight', label: '八棱柱体', thumbnail: './glb/thumbnail/cylinder.png' },
    {checkedlocked: false, component: 'ShapeA', name: 'shapea', label: '形状a', thumbnail: './glb/thumbnail/shapea.png' },
    {checkedlocked: false, component: 'ConeCrossFourSide', name: 'conecrossfourside', label: '形状b', thumbnail: './glb/thumbnail/conecrossfourside.png' },
    {checkedlocked: false, component: 'ConeCross', name: 'conecross', label: '圆锥穿插体', thumbnail: './glb/thumbnail/conecross.png' },
    {checkedlocked: false, component: 'BoxCross', name: 'boxcross', label: '十字穿插体', thumbnail: './glb/thumbnail/boxcross.png' },
    {checkedlocked: false, component: 'Icosahedron', name: 'icosahedron', label: '多面', thumbnail: './glb/thumbnail/icosahedron.png' },
    {checkedlocked: false, component: 'Dodecahedron', name: 'dodecahedron', label: '正十二面体', thumbnail: './glb/thumbnail/dodecahedron.png' },
    {checkedlocked: false, component: 'CupHandle', name: 'cupHandle', label: '手柄杯', thumbnail: './glb/thumbnail/cuphandle.png' },
    {checkedlocked: false, component: 'CupHandleB', name: 'cupHandleB', label: '手柄杯2', thumbnail: './glb/thumbnail/cuphandleb.png' },
    {checkedlocked: false, component: 'CupHandleC', name: 'cupHandleC', label: '手柄杯3', thumbnail: './glb/thumbnail/cuphandlec.png' },
    {checkedlocked: false, component: 'PlateA', name: 'PlateA', label: '盘子A', thumbnail: './glb/thumbnail/platea.png' },
    {checkedlocked: false, component: 'PlateB', name: 'PlateB', label: '盘子B', thumbnail: './glb/thumbnail/plateb.png' },
    {checkedlocked: false, component: 'PlateC', name: 'PlateC', label: '盘子C', thumbnail: './glb/thumbnail/platec.png' },
    {checkedlocked: false, component: 'Goblet', name: 'goblet', label: '高脚杯', thumbnail: './glb/thumbnail/goblet.png' },
    {checkedlocked: false, component: 'WineBottle', name: 'winebottle', label: '酒瓶', thumbnail: './glb/thumbnail/winebottle.png' },
    {checkedlocked: false, component: 'Egg', name: 'egg', label: '鸡蛋', thumbnail: './glb/thumbnail/egg.png' },
    {checkedlocked: false, component: 'Pear', name: 'pear', label: '鸡蛋', thumbnail: './glb/thumbnail/pear.png' },
    {checkedlocked: false, component: 'Apple', name: 'apple', label: '苹果', thumbnail: './glb/thumbnail/apple.png' },
    {checkedlocked: false, component: 'JarA', name: 'jara', label: '坛子a', thumbnail: './glb/thumbnail/jara.png' },
    {checkedlocked: false, component: 'JarB', name: 'jarb', label: '坛子b', thumbnail: './glb/thumbnail/jarb.png' },
    {checkedlocked: false, component: 'Vasea', name: 'vasea', label: '花瓶a', thumbnail: './glb/thumbnail/vasea.png' },
    {checkedlocked: false, component: 'Vaseb', name: 'vaseb', label: '花瓶a', thumbnail: './glb/thumbnail/vaseb.png' },
    {checkedlocked: false, component: 'Vasec', name: 'vasec', label: '花瓶a', thumbnail: './glb/thumbnail/vasec.png' },
    {checkedlocked: true, component: 'body/Eye', name: 'eye', label: '眼睛', thumbnail: './glb/thumbnail/body/eye.png' },
    {checkedlocked: true, component: 'body/Foot', name: 'foot', label: '脚', thumbnail: './glb/thumbnail/body/foot.png' },
    {checkedlocked: true, component: 'body/Venus', name: 'venus', label: '维纳斯', thumbnail: './glb/thumbnail/body/venus.png' },
    {checkedlocked: true, component: 'body/FemaleBody', name: 'femalebody', label: '女性身体', thumbnail: './glb/thumbnail/body/femalebody.png' },
    {checkedlocked: true, component: 'body/MaleBody', name: 'malebody', label: '男性身体', thumbnail: './glb/thumbnail/body/malebody.png' },
    {checkedlocked: true, component: 'body/Skeleton', name: 'skeleton', label: '骷髅', thumbnail: './glb/thumbnail/body/skeleton.png' },
    {checkedlocked: true, component: 'body/SkeletonB', name: 'skeleton_b', label: '骷髅', thumbnail: './glb/thumbnail/body/skeleton_b.png' },
    {checkedlocked: true, component: 'body/LoomisHead', name: 'loomis_head', label: '简易结构', thumbnail: './glb/thumbnail/body/loomis_head.png' },
    {checkedlocked: true, component: 'body/SkeletonHead', name: 'skeleton_head', label: '骷髅头', thumbnail: './glb/thumbnail/body/skeleton_head.png' },
    {checkedlocked: true, component: 'body/SkeletonHeadD', name: 'skeleton_head_d', label: '骷髅头', thumbnail: './glb/thumbnail/body/skeleton_head_d.png' },
    {checkedlocked: true, component: 'body/HeadReference', name: 'head_reference', label: '头部块面', thumbnail: './glb/thumbnail/body/head_reference.png' },
    {checkedlocked: true, component: 'body/SculptureBustOfRozaLoewenfeld', name: 'sculpture_bust_of_roza_loewenfeld', label: '雕塑_胸像_罗扎_卢文菲尔德', thumbnail: './glb/thumbnail/body/sculpture_bust_of_roza_loewenfeld.png' },
    {checkedlocked: true, component: 'body/SkullProportionsKeyLandmarks', name: 'skull_proportions_key_landmarks', label: '概况骷髅头', thumbnail: './glb/thumbnail/body/skull_proportions_key_landmarks.png' },
    {checkedlocked: true, component: 'body/PlanesOfTheHeadAndrewLoomisMethod', name: 'planes_of_the_head_andrew_loomis_method', label: '模型比列', thumbnail: './glb/thumbnail/body/planes_of_the_head_andrew_loomis_method.png' },
    {checkedlocked: true, component: 'body/SkeletonHeadC', name: 'skeleton_head_c', label: '模型比列2', thumbnail: './glb/thumbnail/body/skeleton_head_c.png' },
    {checkedlocked: true, component: 'body/HeadOfDavid', name: 'head_of_david', label: '大卫头像', thumbnail: './glb/thumbnail/body/head_of_david.png' },
    {checkedlocked: true, component: 'body/DavidBowieFaceAnatomy', name: 'David_Bowie_Face_Anatomy', label: '头部肌肉', thumbnail: './glb/thumbnail/body/david_bowie_face_anatomy.png' },
    {checkedlocked: true, component: 'body/OldManHeadMiquelBlay', name: 'old_man_head_miquel_blay', label: '老人石膏像', thumbnail: './glb/thumbnail/body/old_man_head_miquel_blay.png' },
    {checkedlocked: true, component: 'body/Head8FromHeadsBundle2', name: 'head_8_from_heads_bundle_2', label: '老人石膏像', thumbnail: './glb/thumbnail/body/head_8_from_heads_bundle_2.png' },
    {checkedlocked: true, component: 'body/MultinodularGoitre', name: 'multinodular_goitre', label: '骨骼', thumbnail: './glb/thumbnail/body/multinodular_goitre.png' },
    {checkedlocked: true, component: 'body/EcorcheHead', name: 'ecorche_head', label: '模型', thumbnail: './glb/thumbnail/body/ecorche_head.png' },
    {checkedlocked: true, component: 'body/PlanarHeadByOlegToropyginB', name: 'planar_head_by_oleg_toropygin_b', label: '模型', thumbnail: './glb/thumbnail/body/planar_head_by_oleg_toropygin_b.png' },
    
];

